/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.informatica.servidor.presentacion;

import java.awt.Canvas;

/**
 *
 * @author harol
 */
public class Vista extends javax.swing.JFrame {
    
    //VARIABLES
    //private Controlador control;
    private Modelo modelo;

    
    //GETTERS
    public Modelo getModelo() {
        return modelo;
    }
    
//    public Controlador getControl() {
//        if(control == null){
//            control = new Controlador(this);
//        }
//        return control;
//    }
    
    /**
     * Constructor de la vista 
     * @param m 
     */
    public Vista(Modelo m) {
        modelo = m;
        initComponents();
        //asignarEventos();
    }

    
    
//    private void asignarEventos() {
//        sldFalangeDigIzq.addChangeListener(getControl());
//        sldFalangeDigDer.addChangeListener(getControl());
//        sldFalangeProxIzq.addChangeListener(getControl());
//        sldFalangeProxDer.addChangeListener(getControl());
//        sldMano.addChangeListener(getControl());
//        sldAnteBrazo.addChangeListener(getControl());
//        sldBrazo.addChangeListener(getControl());
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCanvas = new javax.swing.JPanel();
        lienzo = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCanvas.setBackground(new java.awt.Color(255, 255, 255));
        PanelCanvas.setPreferredSize(new java.awt.Dimension(300, 300));

        lienzo.setBackground(new java.awt.Color(204, 204, 204));
        lienzo.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout PanelCanvasLayout = new javax.swing.GroupLayout(PanelCanvas);
        PanelCanvas.setLayout(PanelCanvasLayout);
        PanelCanvasLayout.setHorizontalGroup(
            PanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCanvasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelCanvasLayout.setVerticalGroup(
            PanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCanvasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lienzo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //GETTERS DE LOS COMPONENTES DEL FRAME
    public Canvas getLienzo() {
        return lienzo;
    }

//    public JSlider getSldrFalangeDigIzq() {
//        return sldFalangeDigIzq;
//    }
//
//    public JSlider getSldFalangeDigDer() {
//        return sldFalangeDigDer;
//    }
//
//    public JSlider getSldFalangeProxDer() {
//        return sldFalangeProxDer;
//    }
//
//    public JSlider getSldFalangeProxIzq() {
//        return sldFalangeProxIzq;
//    }
//
//    public JSlider getSldMano() {
//        return sldMano;
//    }
//
//    public JSlider getSldAnteBrazo() {
//        return sldAnteBrazo;
//    }
//
//    public JSlider getSldBrazo() {
//        return sldBrazo;
//    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCanvas;
    private java.awt.Canvas lienzo;
    // End of variables declaration//GEN-END:variables
}
